services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    restart: unless-stopped
    ports:
      - "1883:1883"      # MQTT port      
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight port
    volumes:
      - ./redis/data:/data  
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis_hydration:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: redis_hydration
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mqtt
      - redis
    networks:
      - advanced_data_management
    volumes:
      - ./redis_hydration.yaml:/connect.yaml

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    restart: unless-stopped
    command: 
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    ports:
      - "18081:18081"  # Schema Registry (external)
      - "18082:18082"  # Pandaproxy (external)
      - "19092:19092"  # Kafka API (external)
      - "19644:9644"   # Admin API
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - advanced_data_management    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - "8080:8080"  
    depends_on:
      - redpanda        
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  mqtt_kafka_bridge:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: mqtt_kafka_bridge
    restart: unless-stopped
    volumes:
      - ./mqtt_kafka_bridge.yaml:/connect.yaml
    depends_on:
      - mqtt
      - redpanda
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  advanced_data_management:
    driver: bridge

volumes:
  redpanda_data: