version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1883:1883"      # MQTT port
      - "9001:9001"      # WebSocket port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - advanced_data_management

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight port
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis_hydration:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: redis_hydration
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mqtt
      - redis
    networks:
      - advanced_data_management
    volumes:
      - ./redis_hydration.yaml:/connector.yaml

networks:
  advanced_data_management:
    driver: bridge