{
 "title": "Live Dashboard",
 "time": { "from": "2025-10-29T09:37:08.012Z", "to": "2025-10-29T10:41:59.013Z" },
 "panels": [
  {
   "title": "Fill Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "beverage_data",
     "rawSql": "SELECT \r\n    time,\r\n    metric,\r\n    value\r\nFROM beverage_metrics\r\nWHERE metric IN ('process_fill_volume_target', 'process_fill_volume_actual')\r\n    AND line = 'filling-line-1'\r\n    AND time > NOW() - INTERVAL '5 minutes'\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Line Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "beverage_data",
     "rawSql": "SELECT \r\n    time,\r\n    metric,\r\n    value\r\nFROM beverage_metrics\r\nWHERE metric IN ('process_line_speed_target', 'process_line_speed_actual')\r\n    AND line = 'filling-line-1'\r\n    AND time > NOW() - INTERVAL '5 minutes'\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Good Bottles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "beverage_data",
     "rawSql": "SELECT \r\n    CAST(value AS BIGINT) as \"Good Bottles\"\r\nFROM latest_metrics\r\nWHERE metric = 'counters_good_bottles' AND line = 'filling-line-1';"
    }
   ]
  },
  {
   "title": "Bad Bottles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "beverage_data",
     "rawSql": "SELECT \r\n    CAST(value AS BIGINT) as \"Bad Bottles\"\r\nFROM latest_metrics\r\nWHERE metric = 'counters_bad_bottles_total' AND line = 'filling-line-1';"
    }
   ]
  },
  {
   "title": "Production Progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "beverage_data",
     "rawSql": "SELECT \r\n    value as \"Progress\"\r\nFROM latest_metrics\r\nWHERE metric = 'production_progress_percent' AND line = 'filling-line-1';"
    }
   ]
  }
 ]
}