input:
  label: "mqtt_in"
  mqtt:
    urls:
      - "tcp://mosquitto-broker:1883"
    client_id: "mqtt_kafka_bridge_a5b3c8d1"
    keepalive: 60
    clean_session: true
    topics:
      - "v1/best-beverage/+/+/+/+"
    qos: 1

pipeline:
  processors:
    - mapping: |
        let topic = meta("mqtt_topic").or("")
        let parts = topic.split("/")
        root.metadata.mqtt_topic = topic
        root.metadata.version = parts.index(0).or("unknown")
        root.metadata.enterprise = parts.index(1).or("unknown")
        root.metadata.site = parts.index(2).or("unknown")
        root.metadata.area = parts.index(3).or("unknown")
        root.metadata.line = parts.index(4).or("unknown")
        root.metadata.metric = parts.index(5).or("unknown")
        root.timestamp = this.timestamp
        root.value = this.value

output:
  label: "kafka_out"
  kafka:
    addresses:
      - "redpanda:9092"
    topic: "beverage.production.metrics"
    key: '${! this.metadata.line + "-" + this.metadata.metric }'
    partitioner: "murmur2_hash"
    compression: snappy
    max_in_flight: 1
    metadata:
      exclude_prefixes: []

metrics:
  prometheus:
    use_histogram_timing: true
    histogram_buckets: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0]

logger:
  level: INFO
  format: json
  add_timestamp: true