input:
  label: "mqtt_in"
  mqtt:
    urls:
      - "tcp://mosquitto-broker:1883"
    client_id: "enrichment-pipeline-7a3f91c2-5eb4-4d12-bc89-e8f7a2d1c9e3"
    keepalive: 60
    clean_session: true
    topics:
      # Subscribe to key metrics that benefit from enrichment
      - "v1/best-beverage/+/+/+/machine_status"
      - "v1/best-beverage/+/+/+/process_fill_volume_actual"
      - "v1/best-beverage/+/+/+/alarms_active"
      - "v1/best-beverage/+/+/+/counters_good_bottles_order"

pipeline:
  processors:
    # Step 1: Parse the original MQTT message
    - mapping: |
        root.timestamp = this.timestamp
        root.value = this.value
        root.metric_name = meta("mqtt_topic").split("/").index(-1)
        root.line = meta("mqtt_topic").split("/").index(-2)
        root.area = meta("mqtt_topic").split("/").index(-3)
        root.site = meta("mqtt_topic").split("/").index(-4)
        root.enterprise = meta("mqtt_topic").split("/").index(-5)
        root.mqtt_topic = meta("mqtt_topic")

    # Step 2: Enrich with context from Redis using branch processor
    - branch:
        request_map: 'root.key = this.line'
        processors:
          - redis:
              url: "redis://redis_container:6379"
              command: hmget
              args_mapping: |
                root = [ 
                  this.key,
                  "production_order",
                  "production_article", 
                  "production_quantity",
                  "production_lot_number",
                  "machine_name",
                  "machine_serial_number",
                  "machine_plant",
                  "counters_total_bottles_order",
                  "production_progress_percent"
                ]
        result_map: |
          root.context.production_order = this.0
          root.context.article = this.1
          root.context.quantity = this.2.number().catch(null)
          root.context.lot_number = this.3
          root.context.machine_name = this.4
          root.context.machine_serial_number = this.5
          root.context.plant = this.6
          root.context.total_bottles_order = this.7.number().catch(null)
          root.context.progress_percent = this.8.number().catch(null)

    # Step 3: Create final enriched message
    - mapping: |
        root.timestamp = this.timestamp
        root.metric = this.metric_name
        root.value = this.value
        root.location = {
          "enterprise": this.enterprise,
          "site": this.site,
          "area": this.area,
          "line": this.line
        }
        root.production_context = this.context
        root.source_topic = this.mqtt_topic

output:
  label: "kafka_out"
  kafka:
    addresses:
      - "redpanda_broker:9092"
    topic: "beverage_filling_enriched"
    key: ${! meta("mqtt_topic") }
    max_in_flight: 1
    compression: snappy